import { SyntaxType as Syntax } from "./SyntaxType";

export const Keywords = new Map<string, Syntax>(Object.entries({
    "break": Syntax.BREAK,
    "const": Syntax.CONST,
    "continue": Syntax.CONTINUE,
    "else": Syntax.ELSE,
    "false": Syntax.FALSE,
    "for": Syntax.FOR,
    "global": Syntax.GLOBAL,
    "if": Syntax.IF,
    "local": Syntax.LOCAL,
    "method": Syntax.METHOD,
    "null": Syntax.NULL,
    "print": Syntax.PRINT,
    "private": Syntax.PRIVATE,
    "public": Syntax.PUBLIC,
    "raise": Syntax.RAISE,
    "return": Syntax.RETURN,
    "super": Syntax.SUPER,
    "static": Syntax.STATIC,
    "this": Syntax.THIS,
    "true": Syntax.TRUE,
    "while": Syntax.WHILE,
}));