export enum SyntaxType {
    // Single-character tokens.
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR,
    CARAT, PERCENT, HASHTAG,

    // One or two character tokens.
    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,
    PLUS_EQUALS, MINUS_EQUALS,
    STAR_EQUALS, SLASH_EQUALS,
    CARAT_EQUALS, PERCENT_EQUALS,
    AND_EQUALS, OR_EQUALS,
    PLUS_PLUS, MINUS_MINUS,

    // Literals.
    IDENTIFIER, STRING, NUMBER,

    // Keywords.
    AND, BREAK, CONTINUE, CLASS, ELSE, FALSE, METHOD, FOR, 
    IF, NULL, OR, PRINT, RETURN, SUPER, THIS, TRUE, LET, 
    CONST, WHILE, RAISE,

    EOF
}