export enum SyntaxType {
    // Single-character tokens.
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR,
    CARAT, PERCENT, HASHTAG,

    // One or two character tokens.
    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,
    PLUS_EQUAL, MINUS_EQUAL,
    STAR_EQUAL, SLASH_EQUAL,
    CARAT_EQUAL, PERCENT_EQUAL,
    AND_EQUAL, OR_EQUAL,
    PLUS_PLUS, MINUS_MINUS,
    COLON, COLON_COLON,

    // Literals.
    IDENTIFIER, STRING, NUMBER,

    // Keywords.
    AND, BREAK, CONTINUE, CLASS, ELSE, FALSE, METHOD, FOR,
    IF, NULL, OR, PRINT, RETURN, SUPER, THIS, TRUE, LOCAL,
    CONST, WHILE, RAISE, GLOBAL, PUBLIC, PRIVATE, STATIC,

    EOF
}